name: Client CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mod:
    name: Module Download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v2.1.7
        with:
          path: ./client/node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node
        if: steps.mod-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install npm
        if: steps.mod-cache.outputs.cache-hit != 'true'
        run: npm install -g npm@7
      - name: Module Download
        if: steps.mod-cache.outputs.cache-hit != 'true'
        run: cd ./client && npm ci
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v2.1.7
        with:
          path: ./client/node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: run lint
        run: cd ./client && npm run lint
  type:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v2.1.7
        with:
          path: ./client/node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: run type-check
        run: cd ./client && npm run type-check
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v2.1.7
        with:
          path: ./client/node_modules
          key: mod-${{ hashFiles('**/package-lock.json') }}
      - name: run build
        run: cd ./client && npm run build
        env:
          NODE_ENV: production
